### ISSUE TITLE
Lab 5 issue

### ISSUE THREAD

**Issue by chrispjgavin** [aws-samples/aws-serverless-saas-workshop#11]
**When I run deployment.sh -s I get some errors early on:**

node_modules/@types/prettier/index.d.ts:41:54 - error TS2315: Type 'IsTuple' is not generic.

41 type IndexProperties<T extends { length: number }> = IsTuple<T> extends true
                                                        ~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:53:6 - error TS2456: Type alias 'IsTuple' circularly references itself.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
        ~~~~~~~

node_modules/@types/prettier/index.d.ts:53:65 - error TS2574: A rest element type must be an array type.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                   ~~~~~~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:53:84 - error TS2315: Type 'IsTuple' is not generic.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                                      ~~~~~~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:96:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

96     call<
       ~~~~

node_modules/@types/prettier/index.d.ts:131:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

131     each<
        ~~~~

node_modules/@types/prettier/index.d.ts:165:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

165     map<
        ~~~

**--- Then I get some more errors:**

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pipeline@0.1.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the pipeline@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2022-06-08T21_36_28_379Z-debug.log

And this is the log:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v14.18.1/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v14.18.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle pipeline@0.1.0~prebuild: pipeline@0.1.0
6 info lifecycle pipeline@0.1.0~build: pipeline@0.1.0
7 verbose lifecycle pipeline@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle pipeline@0.1.0~build: PATH: /home/ec2-user/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/environment/aws-serverless-saas-workshop/Lab5/server/TenantPipeline/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v14.18.1/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3@global/bin:/home/ec2-user/.rvm/rubies/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3/bin:/home/ec2-user/.rvm/gems/ruby-2.6.3@global/bin:/home/ec2-user/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/home/ec2-user/.rvm/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/bin:/home/ec2-user/.rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin
9 verbose lifecycle pipeline@0.1.0~build: CWD: /home/ec2-user/environment/aws-serverless-saas-workshop/Lab5/server/TenantPipeline
10 silly lifecycle pipeline@0.1.0~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle pipeline@0.1.0~build: Returned: code: 2  signal: null
12 info lifecycle pipeline@0.1.0~build: Failed to exec build script
13 verbose stack Error: pipeline@0.1.0 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid pipeline@0.1.0
15 verbose cwd /home/ec2-user/environment/aws-serverless-saas-workshop/Lab5/server/TenantPipeline
16 verbose Linux 4.14.281-212.502.amzn2.x86_64
17 verbose argv "/home/ec2-user/.nvm/versions/node/v14.18.1/bin/node" "/home/ec2-user/.nvm/versions/node/v14.18.1/bin/npm" "run" "build"
18 verbose node v14.18.1
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 2
22 error pipeline@0.1.0 build: `tsc`
22 error Exit status 2
23 error Failed at the pipeline@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**So, at the Login to the SaaS application page I don't see the enter your tenant name and click login below**

**Comment by chrispjgavin** [comment]
Cracked it and learned a lot! I tracked it down to an issue with Angular which I resolved by following an install process of Angular on Cloud9. Cost me a few extra bucks leaving the solution up for a few days but worth it for the learning :)
