### ISSUE TITLE
Product service raises `TypeError` when entering decimal value for product price

### ISSUE THREAD

**Issue by iamsouravin** [aws-samples/aws-serverless-saas-workshop#44]
**Issue:** Entering decimal value for product price raises `TypeError`.

**Description:** `product_service.py` uses `json.loads` to unmarshall product info for DynamoDB create or update calls. When user enters decimal value for product price it gets encoded as float type which raises `TypeError` from DDB.

```
2022-11-10T20:55:16.996+00:00
[ERROR] TypeError: Float types are not supported. Use Decimal types instead.
Traceback (most recent call last):
  File "/var/task/aws_lambda_powertools/tracing/tracer.py", line 305, in decorate
    response = lambda_handler(event, context, **kwargs)
  File "/var/task/product_service.py", line 36, in create_product
    product = product_service_dal.create_product(event, payload)
  File "/var/task/product_service_dal.py", line 69, in create_product
    response = table.put_item(
  File "/var/runtime/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/var/runtime/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/task/botocore/client.py", line 515, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore
    return xray_recorder.record_subsegment(
  File "/var/task/aws_xray_sdk/core/recorder.py", line 436, in record_subsegment
    return_value = wrapped(*args, **kwargs)
  File "/var/task/botocore/client.py", line 893, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/task/botocore/client.py", line 961, in _convert_to_request_dict
    api_params = self._emit_api_params(
  File "/var/task/botocore/client.py", line 1000, in _emit_api_params
    self.meta.events.emit(
  File "/var/task/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/task/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/var/task/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/var/runtime/boto3/dynamodb/transform.py", line 195, in inject_attribute_value_input
    self._transformer.transform(
  File "/var/runtime/boto3/dynamodb/transform.py", line 253, in transform
    self._transform_parameters(
  File "/var/runtime/boto3/dynamodb/transform.py", line 260, in _transform_parameters
    getattr(self, '_transform_%s' % type_name)(
  File "/var/runtime/boto3/dynamodb/transform.py", line 274, in _transform_structure
    self._transform_parameters(
  File "/var/runtime/boto3/dynamodb/transform.py", line 260, in _transform_parameters
    getattr(self, '_transform_%s' % type_name)(
  File "/var/runtime/boto3/dynamodb/transform.py", line 285, in _transform_map
    params[key] = transformation(value)
  File "/var/runtime/boto3/dynamodb/types.py", line 105, in serialize
    dynamodb_type = self._get_dynamodb_type(value)
  File "/var/runtime/boto3/dynamodb/types.py", line 118, in _get_dynamodb_type
    elif self._is_number(value):
  File "/var/runtime/boto3/dynamodb/types.py", line 162, in _is_number
    raise TypeError(
```

**Workaround:** Existing code allows integer price values from UI. Avoid entering decimal price value for product.

**Fix:** Add `parse_float: Decimal` argument in `json.loads` to encode floating point values to `Decimal` type.

**Comment by ujwalbukka** [comment]
Hi @iamsouravin 

Thanks for reporting this issue and fix. We are currently working on fixing this.

**Comment by ujwalbukka** [comment]
Hi @iamsouravin 

Thanks for reporting the issue and for the fix, appreciate it. We need to do the same fix for order service too. 
Please let us know if you will be able to update the PR with order service fix too.
