### ISSUE TITLE
Lab 5 : platinum tier are not getting created

### ISSUE THREAD

**Issue by Preet2fun** [aws-samples/aws-serverless-saas-workshop#51]
2023-02-24T12:51:14.210+05:30Copy[ERROR] PipelineNotFoundException: An error occurred (PipelineNotFoundException) when calling the StartPipelineExecution operation: Pipeline with name serverless-saas-pipeline does not exist in account 252007810724.Traceback (most recent call last):  File "/opt/python/aws_lambda_powertools/tracing/tracer.py", line 305, in decorate    response = lambda_handler(event, context, **kwargs)  File "/var/task/tenant-provisioning.py", line 36, in provision_tenant    response_codepipeline = codepipeline.start_pipeline_execution(  File "/opt/python/botocore/client.py", line 530, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/opt/python/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore    return xray_recorder.record_subsegment(  File "/opt/python/aws_xray_sdk/core/recorder.py", line 462, in record_subsegment    six.raise_from(exc, exc)  File "<string>", line 3, in raise_from  File "/opt/python/aws_xray_sdk/core/recorder.py", line 457, in record_subsegment    return_value = wrapped(*args, **kwargs)  File "/opt/python/botocore/client.py", line 960, in _make_api_call    raise error_class(parsed_response, operation_name) | [ERROR] PipelineNotFoundException: An error occurred (PipelineNotFoundException) when calling the StartPipelineExecution operation: Pipeline with name serverless-saas-pipeline does not exist in account 252007810724. Traceback (most recent call last):   File "/opt/python/aws_lambda_powertools/tracing/tracer.py", line 305, in decorate     response = lambda_handler(event, context, **kwargs)   File "/var/task/tenant-provisioning.py", line 36, in provision_tenant     response_codepipeline = codepipeline.start_pipeline_execution(   File "/opt/python/botocore/client.py", line 530, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/opt/python/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore     return xray_recorder.record_subsegment(   File "/opt/python/aws_xray_sdk/core/recorder.py", line 462, in record_subsegment     six.raise_from(exc, exc)   File "<string>", line 3, in raise_from   File "/opt/python/aws_xray_sdk/core/recorder.py", line 457, in record_subsegment     return_value = wrapped(*args, **kwargs)   File "/opt/python/botocore/client.py", line 960, in _make_api_call     raise error_class(parsed_response, operation_name)
-- | --

**Comment by ujwalbukka** [comment]
Looks like the pipeline build has failed. Please take latest code from repo(updated typescript version) and rerun Lab5 from the beginning. We tested on our end and we were able to onboard platinum tier tenant.

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you have questions/issues
